language: c

before_install:
  - export EXECUTABLE=bin/ush-debug
  - export STRIPBIN=bin/ush-bin

script:
  - make clean
  - make
  - make strip
  - bin/ush-bin --help
  
after_success:
  - echo "Success!"
